#!/bin/bash

# export PATH=$PATH:/media/viviane/MYAPPS/gurudavivi/@guru-cli/guru-cli/bin

# node -r esbuild-register ./src/index.ts $@

# CMD='remove -D jest @types/jest ts-jest'
# CMD='add -D jest@^27.5.1 @types/jest ts-jest@27.0.0'

CMD='add -D @guru/tsconfig @guru/eslint-config'


pnpm --filter ./packages/box -r $CMD
pnpm --filter ./packages/table -r $CMD


# pnpm --filter ./packages/term -r --if-present $CMD
# pnpm --filter ./packages/term -r --if-present $CMD
# pnpm --filter ./packages/term -r --if-present $CMD
# pnpm add -w -D jest @types/jest ts-jest @types/node ts-node

# pnpm --filter ./packages -r -p exec pnpm pack  